import type { Metadata } from "next";
import { Open_Sans } from 'next/font/google'
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

const open_sans = Open_Sans({
    weight: ['500'],
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className='my-5 '>
            <Header />
            <Navbar />
            {children}
        </div>
    );
}
